# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='分类名')),
            ],
            options={
                'verbose_name_plural': '网站文章分类表',
            },
        ),
        migrations.CreateModel(
            name='SiteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='分类名')),
            ],
            options={
                'verbose_name_plural': '网站分类表',
            },
        ),
        migrations.AddField(
            model_name='sitearticlecategory',
            name='sitecategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.SiteCategory', verbose_name='所属网站'),
        ),
    ]
